### ISSUE TITLE
The lab instructions not allowing traffic inbound to ALB

### ISSUE THREAD

**Issue by robbiecooray1** [aws-samples/amazon-ec2-native-infrastructure-security-workshop#1]
> Rule #: 100
> Of type All Traffic
> To the Destination 10.0.0.0/8
> And an Allow Behavior

This disallows traffic to the website from the public. Why is it allowed only to the `10.0.0.0/8` scope and not `0.0.0.0/0`?

**Comment by cassiamartin** [comment]
Fixed, thank you, Joshua.
