### ISSUE TITLE
Insufficient permissions for SharedServerConnectivityRole role for SSM agent to create CloudWatch Logs

### ISSUE THREAD

**Issue by dalacan** [aws-samples/amazon-ec2-native-infrastructure-security-workshop#2]
Either the SharedServerConnectivityPolicy policy has insufficient permissions for the SSM agent to run to create the cloud watch logs or the documentation in the [extracredit.md](https://github.com/aws-samples/amazon-ec2-native-infrastructure-security-workshop/blob/master/docs/extracredit.md)  to add permissions to the SharedServerConnectivityRole role documentation are insufficient.

Suggest ensuring the following permissions are added to the SharedServerConnectivityPolicy policy either during the creation of the policy or to the extra credit documentation:
**EC2 Messages**
>     GetMessages

**Systems Manager**
>     ListInstanceAssociations
>     UpdateInstanceAssociations

**Comment by cassiamartin** [comment]
Added to the extracredit instructions.  Thank you for this improvement, Derrick.
